apiVersion: v2
name: frontend
description: Frontend of metrics-server extension.
type: application
version: 0.2.2
appVersion: "1.0.2"
home: https://kubesphere.io
sources:
  - https://github.com/kubesphere

